### ISSUE TITLE
Support for Recurring transactions

### ISSUE THREAD

**Issue by spiftire** [vippsas/deno-sdk#69]
**Is your feature request related to a problem? Please describe.**
I now have to use the REST API to achieve my goals related to recurring transactions. It would be nice to handle this through the SDK.

**Describe the solution you'd like**
I would love to call the vipps SDK client like so
```ts
const client = Client({...clientConfig})
client.recurring.someAction({...actionConfig})
```

**Describe alternatives you've considered**
Using the REST API as is.

**Additional context**
https://developer.vippsmobilepay.com/docs/APIs/recurring-api/recurring-api-quick-start/

**Comment by tomas-zijdemans-vipps** [comment]
Hi @spiftire! Thanks for reporting this. 
Recurring was removed in release 2.0.0, since it was unused. You can use release 1.3.4 for recurring.
I'm happy to bring Recurring back if you need it 😄 
(Would also love to hear from you about what merchant you would be integrating, if you have any further requirements or questions, etc.)

**Comment by spiftire** [comment]
I would love it if you could bring it back. That would make my life easier 😄

**Comment by tomas-zijdemans-vipps** [comment]
👍 
I'll bring it back within the next couple of days

**Comment by tomas-zijdemans-vipps** [comment]
Fixed in latest release. Please test it out and let me know how it goes :)
